"use client";
import {useEffect,useState} from "react";
export default function Subs(){
 const [rows,setRows]=useState<any[]>([]),[users,setUsers]=useState<any[]>([]),[configs,setConfigs]=useState<any[]>([]),[open,setOpen]=useState(false),[b,setB]=useState<any>({user_id:"",traffic_limit:100*1073741824,expires_at:"",config_ids:[]});
 async function load(){const [a,c,u]=await Promise.all([fetch("/api/subscriptions"),fetch("/api/configs"),fetch("/api/users")]);setRows(await a.json());setConfigs(await c.json());setUsers(await u.json())}
 useEffect(()=>{load()},[]);
 async function save(){await fetch("/api/subscriptions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(b)});setOpen(false);load()}
 const base=typeof window!=="undefined"?window.location.origin:"";
 return <><div className="pagehead"><div><h1>اشتراک‌ها</h1><p>ساخت لینک عمومی، کپی همه کانفیگ‌ها و صفحه وضعیت.</p></div><button className="btn" onClick={()=>setOpen(true)}>+ ساخت لینک</button></div><section className="card glass tablecard" style={{marginTop:0}}><div className="tablewrap"><table><thead><tr><th>توکن</th><th>کاربر</th><th>حجم</th><th>انقضا</th><th>لینک</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td className="ip">{r.token.slice(0,12)}…</td><td>{users.find((u:any)=>u.id===r.user_id)?.username||"—"}</td><td>{Math.round(Number(r.traffic_limit)/1073741824)} GB</td><td>{r.expires_at?new Date(r.expires_at).toLocaleDateString("fa-IR"):"—"}</td><td><button className="mini" onClick={()=>navigator.clipboard.writeText(`${base}/sub/${r.token}`)}>کپی لینک</button></td></tr>)}</tbody></table></div></section>{open&&<div className="modal"><div className="modalbox glass"><h3>ساخت Subscription</h3><div className="field"><label>کاربر</label><select value={b.user_id} onChange={e=>setB({...b,user_id:e.target.value})}><option value="">انتخاب کاربر</option>{users.filter((x:any)=>x.role!=="admin").map((u:any)=><option key={u.id} value={u.id}>{u.username}</option>)}</select></div><div className="field"><label>کانفیگ‌ها</label><select multiple value={b.config_ids} onChange={e=>setB({...b,config_ids:Array.from(e.target.selectedOptions).map(x=>x.value)})}>{configs.map((c:any)=><option key={c.id} value={c.id}>{c.name} · {c.protocol}</option>)}</select></div><div className="formgrid"><div className="field"><label>حجم GB</label><input value={Number(b.traffic_limit)/1073741824} onChange={e=>setB({...b,traffic_limit:Number(e.target.value)*1073741824})}/></div><div className="field"><label>انقضا</label><input type="date" value={b.expires_at} onChange={e=>setB({...b,expires_at:e.target.value})}/></div></div><div className="actions"><button className="btn" onClick={save}>ساخت لینک</button><button className="btn secondary" onClick={()=>setOpen(false)}>لغو</button></div></div></div>}</>
}
